Web_Page/web_project/predict/urls.py
from django.urls import path
from . import views

app_name = "predict"

urlpatterns = [
    path('', views.predict, name='prediction_page'),
    path('predict/', views.predict_chances, name='submit_prediction'),
    # path('results/', views.view_results, name='results'),
]

Web_Page/web_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Web_Page/web_project/web_project1/urls.py
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("predict.urls",namespace='predict')),

]

Web_Page/web_project/predict/models.py
from django.db import models

# Create your models here.

Web_Page/web_project/predict/views.py
from django.shortcuts import render
from django.http import JsonResponse
import pandas as pd
# from .models import PredResults

def predict(request):
    return render(request,'predict.html')

def predict_chances(request):
    if request.POST.get('action') == 'post':
        # Receive data from client
        age = float(request.POST.get('age'))
        duration = float(request.POST.get('duration'))
        campaign = float(request.POST.get('campaign'))
        pdays = float(request.POST.get('pdays'))
        previous = float(request.POST.get('previous'))
        model = pd.read_pickle('/Users/hindsalem/Desktop/Project_Portuguese_Bank/Data/Dataset/model.pickle')
        # # Make prediction
        result = model.predict([[age, duration, campaign, pdays, previous]])
        classification=result[0]
        # PredResults.objects.create(age=age, duration=duration, campaign=campaign,
                                #    pdays=pdays,previous=previous ,classification=classification)
        return JsonResponse({'result':classification,'age':age, 'duration':duration, 'campaign':campaign, 'pdays':pdays, 'previous':previous},
        safe=False)

Web_Page/web_project/predict/templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Iris prediction</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">DB</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

Web_Page/web_project/predict/templates/predict.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>Age: <span id="1"></span></div>
                <div>duration: <span id="2"></span></div>
                <div>campaign: <span id="3"></span></div>
                <div>pdays: <span id="4"></span></div>
                <div>previous: <span id="5"></span></div>
                


                <h5 class="pt-3">Prediction Classification:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>
<!-- ['age', 'duration', 'campaign', 'pdays', 'previous', 'Target',
       'entrepreneur', 'housemaid', 'management', 'retired', 'services',
       'student', 'technician', 'unemployed', 'unknown', 'divorced', 'married',
       'single', 'unknown', 'illiterate', 'unknown', 'no', 'unknown', 'yes',
       'no', 'unknown', 'yes', 'cellular', 'telephone', 'apr', 'aug', 'dec',
       'jul', 'jun', 'mar', 'may', 'nov', 'oct', 'sep', 'fri', 'mon', 'thu',
       'tue', 'wed', 'failure', 'nonexistent', 'success', 'admin', 'basic6y',
       'basic9y', 'basic4y', 'high_school', 'professional_course',
       'university_degree', 'blue_collar', 'self_employed'] -->
<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">

            <h1>The Portuguese Bank's</h1>

            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="age">age</label>
                    <input type="number" step="0.1" class="form-control" id="age" placeholder="" required>
                </div>

                <div class="form-group">
                    <label for="duration">duration</label>
                    <input type="number" step="0.1" class="form-control" id="duration" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="campaign">campaign</label>
                    <input type="number" step="0.1" class="form-control" id="campaign" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="pdays">pdays</label>
                    <input type="number" step="0.1" class="form-control" id="pdays" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="previous">previous</label>
                    <input type="number" step="0.1" class="form-control" id="previous" placeholder="" required>
                </div>
                


                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                age:$('#age').val(),
                duration:$('#duration').val(),
                campaign:$('#campaign').val(),
                pdays :$('#pdays').val(),
                previous :$('#previous').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),

                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("1").innerHTML = json['age']
                document.getElementById("2").innerHTML = json['duration']
                document.getElementById("3").innerHTML = json['campaign']
                document.getElementById("4").innerHTML = json['pdays']
                document.getElementById("5").innerHTML = json['previous']
    
            },
            error : function(xhr,errmsg,err) {
            }
        });
    })
</script>

{% endblock %}

Web_Page/web_project/predict/templates/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Prediction Results</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">age</th>
                <th scope="col">Job</th>
                <th scope="col">Marital</th>
                <th scope="col">Education</th>
                <th scope="col">Housing</th>
                <th scope="col">Loan</th>
                <th scope="col">Contact</th>
                <th scope="col">Month</th>
                <th scope="col">Day of week </th>
                <th scope="col">Duration</th>
                <th scope="col">Campaign</th>
                <th scope="col">Pdays</th>
                <th scope="col">Previous</th>
                <th scope="col">Poutcome</th>

                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.age }}</td>
                    <td>{{ data.job }}</td>
                    <td>{{ data.marital }}</td>
                    <td>{{ data.education }}</td>
                    <td>{{ data.housing }}</td>
                    <td>{{ data.loan }}</td>
                    <td>{{ data.contact }}</td>
                    <td>{{ data.month }}</td>
                    <td>{{ data.day_of_week }}</td>
                    <td>{{ data.duration }}</td>
                    <td>{{ data.campaign }}</td>
                    <td>{{ data.pdays }}</td>
                    <td>{{ data.previous }}</td>
                    <td>{{ data.poutcome }}</td>
                    <td>{{ data.classification }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}